### PR TITLE
README: remove outdated note about a GitHub bug

### PR DESCRIPTION
**Pull request by ioistired**

### CODE REVIEW

**Comment by ioistired** [comment]
I signed it!

**Comment by ioistired** [comment]
Funny that I have to sign a CLA to remove two paragraphs from a markdown file 🤔

**Comment by goldfeder** [comment]
Thanks for the patch, but the bug does not appear to be fixed. Github is still encoding it wrong. I see that modern Safari, like Chrome, now handles the bad encoding correctly, but it's still a github bug.

**Comment by ioistired** [comment]
Oh I see. It's in the HTML output. Seems Firefox handles this braindeath correctly too.

**Pull request closed without merging**
